"""empty message

Revision ID: 9327d9fa99b6
Revises: 374ab7247861
Create Date: 2026-08-30 09:34:27.651880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '9327d9fa99b6'
down_revision: Union[str, Sequence[str], None] = '374ab7247861'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('progresoleccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lesson_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('completada', sa.Boolean(), nullable=False),
    sa.Column('usuario_email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('progresoleccion', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_progresoleccion_lesson_id'), ['lesson_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_progresoleccion_usuario_email'), ['usuario_email'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('progresoleccion', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_progresoleccion_usuario_email'))
        batch_op.drop_index(batch_op.f('ix_progresoleccion_lesson_id'))

    op.drop_table('progresoleccion')
    # ### end Alembic commands ###
